# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  encoding: unicode
  database: db/development_db
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  encoding: unicode
  database: db/test_db
  pool: 5
  timeout: 5000
production:
  encoding: unicode
  adapter: postgresql
  database: db/production_db
  pool: 5
  timeout: 5000
